export const SET_RECIPES = 'SET_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const RECIPE_FETCHED = 'RECIPE_FETCHED';
export const RECIPE_UPDATED = 'RECIPE_UPDATED';
export const RECIPE_DELETED = 'RECIPE_DELETED';

export const SET_VISIBILITY = 'SET_VISIBILITY';
export const SET_SORT = 'SET_SORT';
export const RESET_FILTERS = 'RESET_FILTERS';